### ISSUE TITLE
no menu work

### ISSUE THREAD

**Issue by phil123456** [wattostudios/GameExtractor#22]
I keep clicking on open archive menus here and there, no open window pops up
no error , nothing

using jre : jre-8u411-windows-x64.exe

ran from the cmd line, with the bat file

```
==== Running Game Extractor ====
INFO: Load Plugin failed for org.watto.ge.plugin.archive.Plugin_BAG of type Archive
ERROR: java.lang.NoClassDefFoundError: org/watto/ge/plugin/viewer/Viewer_BAG_TEX
java.lang.NoClassDefFoundError: org/watto/ge/plugin/viewer/Viewer_BAG_TEX
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.watto.component.WSPluginManager.addPlugin(WSPluginManager.java:76)
        at org.watto.component.WSPluginManager.scanZip(WSPluginManager.java:422)
        at org.watto.component.WSPluginManager.loadPlugins(WSPluginManager.java:246)
        at org.watto.component.WSPluginManager.loadPlugins(WSPluginManager.java:194)
        at org.watto.WSProgram.buildProgram(WSProgram.java:103)
        at org.watto.WSProgram.<init>(WSProgram.java:61)
        at org.watto.ge.GameExtractor.<init>(GameExtractor.java:519)
        at org.watto.ge.GameExtractor.<clinit>(GameExtractor.java:377)
Caused by: java.lang.ClassNotFoundException: org.watto.ge.plugin.viewer.Viewer_BAG_TEX
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
INFO: [WSPluginManager] Plugin location plugins could not be found
INFO: [WSPluginManager] Plugin location bin/org/watto/ge/plugin could not be found
INFO: [WSPluginManager] Plugin location bin/org/watto/component could not be found
```

**Comment by wattostudios** [comment]
Thank you for raising this. Unfortunately there isn't anything in that log file to indicate a problem (those errors are OK) and we haven't had this issue raised with us before.

Could you please try running Game Extractor by using the EXE file, or by double-clicking on the JAR file - either of those is usually more reliable, as the BAT file has a lot more dependency on the users individual PC. If the EXE/JAR still don't work for you, could you please send the log files from the "logs" directory, as hopefully they'll contain a bit more information.

Thanks

**Comment by ksdomino** [comment]
Not sure if it's as simple as this but something similar confused me a bit too as a new user to this app:
Try this: on the Menu bar, Click Tools, Options.
Then without changing any of the options in the sidebar on the right, on the menu bar Click File, Open Archive, Open Archive. You should see that the right sidebar changes to show you your file system. Use this sidebar to browse for your archives and open them that way. Hope this helps!

**Comment by wattostudios** [comment]
We're going to close this issue for now, but please re-open it if it's still a problem for you.
