### ISSUE TITLE
Multiple errors when running from eclipse on linux. GameExtractor cannot find plugins and dependencies.

### ISSUE THREAD

**Issue by Gamebuster19901** [wattostudios/GameExtractor#4]
```
INFO: Missing Setting: Theme_ButterflyLookAndFeel_BackgroundColor
INFO: Missing Setting: Missing Setting: Theme_ButterflyLookAndFeel_DarkColor
INFO: Missing Setting: Theme_ButterflyLookAndFeel_DarkColor
INFO: Missing Setting: Missing Setting: Theme_ButterflyLookAndFeel_MidColor
INFO: Missing Setting: Theme_ButterflyLookAndFeel_MidColor
INFO: Missing Setting: Missing Setting: Theme_ButterflyLookAndFeel_LightColor
INFO: Missing Setting: Theme_ButterflyLookAndFeel_LightColor
INFO: Missing Setting: Missing Setting: NumberOfTasks
INFO: Missing Setting: NumberOfTasks
INFO: The zip file /home/gamebuster/Desktop/Modding/GameExtractor/GameExtractor.jar does not exist.
INFO: The directory /home/gamebuster/Desktop/Modding/GameExtractor/plugins does not exist.
INFO: The directory /home/gamebuster/Desktop/Modding/GameExtractor/bin\org\watto\ge\plugin does not exist.
INFO: The directory /home/gamebuster/Desktop/Modding/GameExtractor/bin\org\watto\component does not exist.
INFO: Missing Image Icon: WSMenu/File
INFO: Missing Image Icon: WSMenu/Manipulate
INFO: Missing Image Icon: WSMenu/Select
INFO: Missing Image Icon: WSMenu/View
INFO: Missing Image Icon: WSMenu/Preview
INFO: Missing Image Icon: WSMenu/Tools
INFO: Missing Image Icon: WSMenu/Help
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at org.watto.component.WSSidePanelHolder.loadPanel(WSSidePanelHolder.java:99)
	at org.watto.component.WSSidePanelHolder.loadPanel(WSSidePanelHolder.java:89)
	at org.watto.component.WSSidePanelHolder.loadPanel(WSSidePanelHolder.java:80)
	at org.watto.ge.GameExtractor.constructInterface(GameExtractor.java:593)
	at org.watto.WSProgram.buildProgram(WSProgram.java:111)
	at org.watto.WSProgram.<init>(WSProgram.java:61)
	at org.watto.ge.GameExtractor.<init>(GameExtractor.java:475)
	at org.watto.ge.GameExtractor.<clinit>(GameExtractor.java:342)
```

I suspect that the issue is that `\` is being used for file paths instead of `File.separator`.

I can confirm that the following directories do actually exist on my system, but GameExtractor cannot find them:

`/home/Desktop/Modding/GameExtractor/bin/org/watto/ge/plugin`
`/home/Desktop/Modding/GameExtractor/bin/org/watto/component`

**Comment by wattostudios** [comment]
Thanks for the report, we're not surprised that there are some issues on Unix systems - although it's a Java application, we've only really designed it for Windows consumption, however would still like to address Unix issues wherever they occur.

These paths are being pulled from file "settings\plugins.xml" - we have adjusted the WSPluginManager to try both Unix and Windows-style path separators when loading plugins, which should hopefully address this issue.
